### ISSUE TITLE
feat: api docs 기능 추가

### ISSUE THREAD

**Issue by hellices** [shinhancard/dev-portal#31]
### Description

[기능] 
backstage에 등록된 서비스의 api를 관리할 수 있는 기능을 제공한다.
api endpoint와 prameter를 관리하도록 함

[주의사항]
api 등록을 강제화할 수 있는 방안이 있을까? 없으면 관리가 안될듯?
api 등록 자동화할 수 있는 방법은?

[참고]
https://github.com/backstage/backstage/blob/master/plugins/api-docs/README.md

**Comment by hellices** [comment]
#71 같이 진행? @YOOMYE89

**Comment by hellices** [comment]
## [참고사항](https://backstage.io/docs/features/software-catalog/descriptor-format#substitutions-in-the-descriptor-format)
1. component 등록 시 swaager.json파일 경로를 포함하여 배포(https://github.com/hellices/nodejs_template/blob/master/catalog-info.yaml)
```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
```

2. 위 파일의 경로를 읽기 허용하도록 backend app-config.yaml에 추가
```yaml
backend:
  reading:
    allow:
      - host: petstore.swagger.io
```

3. backstage에서 컴포넌트 추가 -> create -> register existing component
https://github.com/hellices/nodejs_template/blob/master/catalog-info.yaml 를 등록해본다.
<img width="1061" alt="스크린샷 2023-08-17 오후 5 47 41" src="https://github.com/shinhancard/dev-portal/assets/5661904/d11da0fb-1c77-4110-b99a-86062b0e95bc">
<img width="589" alt="스크린샷 2023-08-17 오후 5 47 52" src="https://github.com/shinhancard/dev-portal/assets/5661904/26a250f2-50f2-45e0-bf1d-b8004a696c00">

4. api 확인 -> api -> petstore -> definition
<img width="1392" alt="스크린샷 2023-08-17 오후 5 50 01" src="https://github.com/shinhancard/dev-portal/assets/5661904/24ac7eaf-3a36-482b-a6a5-c645c54e7c5b">


An API describes an interface that can be exposed by a component. The API can be defined in different formats, like [OpenAPI](https://swagger.io/specification/), [AsyncAPI](https://www.asyncapi.com/docs/specifications/latest/), [GraphQL](https://graphql.org/learn/schema/), [gRPC](https://developers.google.com/protocol-buffers), or other formats.
