### ISSUE TITLE
feat: 프로젝트 문서화 템플릿 기능 추가

### ISSUE THREAD

**Issue by hellices** [shinhancard/dev-portal#38]
### Description

[기능] 
techdoc plugin과 연동하여 프로젝트의 산출물을 문서화할 수 있도록 템플릿을 제공함

예시는 아래와 같음
- 프로젝트의 개요
- 개발 셋팅 방법
- 방화벽 오픈 목록
- ERD
- 설계서
- 아키텍처 문서 등

**Comment by hellices** [comment]
https://backstage.io/docs/features/techdocs/

**Comment by hellices** [comment]
TechDocs is built on top of the [docs like code approach](https://www.docslikecode.com/about/). This, in short, means that you should keep documentation close to the code.

**Comment by hellices** [comment]
# 개발자 포탈 환경구성
techdocs는 mkdocs(python package)를 통해 markdown file을 static file로 작성해주며,
로컬 스토리지 또는 s3 등으로 파일을 저장하여 서비스해주는 기능이다.

for local
로컬모드에서 실행하기 위해서는 mkdocs, mkdocs-techdocs-core 를 설치해야한다.
- Requires Python version >= 3.7
```shell
pip install mkdocs mkdocs-techdocs-core
```
로컬모드로 techdocs를 실행하기 위한 설정

```yaml
# app-config.yaml

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

```

# 컴포넌트(레포지토리) 구성

techdocs는 컴포넌트의 레포지토리에서 mkdocs.yaml파일을 찾으며 여기서 markdown으로 작성된 문서의 경로를 지정한다.
repository structure는 다음과 같다.

```tree
├── catalog-info.yaml # backstage 컴포넌트 설정
├── mkdocs.yaml # techdocs 설정
├── docs # mkdocs에서 지정한 document 경로
    ├── index.md # 파일들...

```

1. techdocs 기능을 오픈하기 위해서는 컴포넌트의 catalog-info.yaml에 아래와 같이 어노테이션을 추가해야 한다.
이 때 techdocs-ref가 지정하는 경로에 mkdocks.yaml파일이 위치해야 한다.

```yaml
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
```

2. mkdocs.yaml은 실제 document의 위치와 어떤 플러그인을 사용할 것인 지 지정한다.
```yaml
site_name: 'example-docs'

nav:
  - Home: index.md # document location

plugins:
  - techdocs-core # use plugin name
```

3. 위와 같이 설정했을 때 doc 폴더에는 index.md파일이 존재하며 이 파일을 static 파일로 제너레이션하게 된다.
