### ISSUE TITLE
feat: software catalog sample 추가

### ISSUE THREAD

**Issue by hemoi** [shinhancard/dev-portal#75]
software catalog sample 추가하기

**Comment by hemoi** [comment]
# Software Catalog local에서 테스트 하기

software catalog 는 기존 생성한 템플릿을 기반으로 repository를 자동으로 생성해주며, 추후 backstage 에서도 다양한 component들을 쉽게 관리할 수 있게 설정해준다

## Github token 

for local test
github repository를 생성하기 위해서는 github token을 발행해야 한다

1. 토큰 생성

![Image](https://github.com/shinhancard/dev-portal/assets/50298955/74d6a7af-7ff1-4e68-9649-f4b5eb17354b)

- github >  Settings > Developer Settings > generate token
- workflow를 체크해야한다

2. 환경변수 등록

```jsx
integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}
```

- 로컬에서 깃헙 레포지토리 생성까지 하기 위해서는 `app-config.yaml` 파일에서 integration.github > token 을 수정해야 한다. (혹은 환경변수 등록)


## template 추가

```yaml
# app-config.yaml

# Local example templates
    - type: file
      target: ../../templates/examples/react-ssr-template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../templates/examples/springboot-grpc-template/template.yaml
      rules:
        - allow: [Template]
```

- 예시로 example templates을 등록하였음
- type은 file과 url중에 선택이 가능하며, url로 설정한 경우에는 template.yaml 파일 경로를 입력하면 된다
- 파일 수정시 새로고침이 아닌 dev-portal을 중지 후 다시 실행해야 함

**Comment by hemoi** [comment]
동적으로 생성하는 가이드는 추후 작성하겠음

**Comment by hemoi** [comment]
# dynamic data 연동

## frontend

frontend dynamic-pick-extension의 경우에는 

```jsx
yarn add --cwd packages/app @premise/plugin-dynamic-pick-extension
yarn add --cwd packages/app @backstage/plugin-scaffolder-react
yarn add --cwd packages/backend @premise/plugin-form-data-backend
```

- 세개의 패키지 설치가 필요하다 (package.json 수정)

향후 Frontend Extension을 개발하여 fieldExtension을 추가하기 위해서는 

```
// App.tsx

{<ScaffolderPage />}>
      <ScaffolderFieldExtensions>
        <DynamicPickFieldExtension />
      </ScaffolderFieldExtensions>
```

packages/app/src/App.tsx 경로에서 Extension을 추가하면 된다

## backend

```tsx
// backend > src > plugin > formData.ts

import { createRouter } from '@premise/plugin-form-data-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { shcardTeamRouter } from '../providers/shcardTeamRouter';

export default async function createPlugin(
    env: PluginEnvironment,
): Promise<Router> {
    return await createRouter(
        {
            logger: env.logger,
        },
        [
            {
                path: '/shcard',
                router: shcardTeamRouter,
            }
        ],
    );
}
```

새로운 plugin을 등록하기 위해서는 FormData.ts를 수정하면 된다

```tsx
// backend > src > providers > shcardTeamRouter.ts

import express from 'express';
import Router from 'express-promise-router';
import { RouterOptions } from '@premise/plugin-form-data-backend';

export async function shcardTeamRouter(
    options: RouterOptions,
): Promise<express.Router> {
    const { logger } = options;
    const router = Router();

    router.get('/teams', async (_, response) => {
        logger.info('shcard teams');
        response.json(['신기술지원팀', '플랫폼개발팀', '코어개발팀', '플랫폼인프라팀', '코어인프라팀']);
    });

    return router;
}
```

- 만약 별도로 API를 수정하기 위해서는 router를 추가하면 되며, 해당 부분에서 로직 수정을 진행하면 쉽게 api를 개발할 수 있다

## 예시
React ssr template에 dynamic form 예제를 연동해 두었다
팀명을 선택할 수 있고, 해당 팀명은 readme.md에 저장되게 된다

```yaml
// template.yaml

...
spec:
  owner: example@shinhan.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        ...
        team:
          title: Team
          type: string
          ui:field: DynamicPickExtension
          ui:options:
            form_data: shcard/teams
            # external_data: https://dummyjson.com/products/categories # 외부 API 직접 연결 가능
    
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          team: ${{ parameters.team }}
....
```

- `properties.ui.options` 에서 `external_data`를 사용하면 외부 Url 사용이 가능하고, 이전에 만든 `form_data plugin`을 사용할 수 있다
- 이때 기존 skeleton template에 parameter를 넘기기 위해서는 해당 예제에서는 `spec.parameters` 에 team 을 추가하였고, 이후 template 에서 사용하기 위해서 `steps.input.values.team`을 추가하였다

**skeleton 결과**

```yaml
# templates/examples/react-ssr-template/skeleton/README.md

# ${{ values.component_id }}

## Description

${{ values.description }}

team : ${{ values.team }}

## Develop

```bash
# install dependencies
$ yarn
# start development server
$ yarn dev
```
```

- readme template에 values.team을 추가하여 사전의 skeleton template에서 사용할 수 있다



![Image](https://github.com/shinhancard/dev-portal/assets/50298955/53ba3a18-454e-4db7-90f2-681c5ae91cd6)
